# workflow to run on scripts only, reuse the binaries from the previous release
name: Scripts

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_type:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check-diff.outputs.changed }}
      
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        name: checkout
        # with:
        #   submodules: recursive
          
      - name: get diff
        run: |
          git fetch --tags origin
          echo CURR_TAG=`git tag --sort "-committerdate" | cut -d$'\n' -f1` >> $GITHUB_ENV
          echo PREV_TAG=`git tag --sort "-committerdate" | cut -d$'\n' -f2` >> $GITHUB_ENV

      - name: check submodules changes
        id: check-diff
        run: |
          echo changed=`git diff $PREV_TAG..$CURR_TAG --name-only -- 3rdparty`
          echo changed=`git diff $PREV_TAG..$CURR_TAG --name-only -- 3rdparty` >> $GITHUB_OUTPUT
  
  run_was_needed:
    runs-on: ubuntu-latest
    needs: check_type
    if: needs.check_type.outputs.changed != ''
    steps:
      - name: changes needed
        run: echo "changes needed"
        
