# workflow to run on scripts only, reuse the binaries from the previous release
name: Scripts

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        name: checkout
        with:
          submodules: recursive
          
      - name: get diff
        run: |
          git fetch -a
          echo CURR_TAG=`git tag --sort "-committerdate" | cut -d$'\n' -f1` >> $GITHUB_ENV
          echo PREV_TAG=`git tag --sort "-committerdate" | cut -d$'\n' -f2` >> $GITHUB_ENV

      - name: check diff
        run: |
          echo $PREV_TAG
          echo $CURR_TAG
